# Generated by Django 3.0.4 on 2020-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Filetuples',
            new_name='Filetuple',
        ),
    ]
