# Generated by Django 2.2.11 on 2020-03-29 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200329_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='rtt',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
